# Generated by Django 2.2.6 on 2019-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0003_flor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='Estado',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='flor'),
        ),
    ]
