# Generated by Django 2.2.6 on 2019-10-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0004_auto_20191030_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flor',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
