# Generated by Django 2.2.6 on 2019-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='imagen',
        ),
    ]
